name: Build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disable shallow clones for static analysis (SonarCloud)

      # JDK
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt

      # Caches
      - name: 'Cache: Maven-Repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
      - name: 'Cache: SonarCloud packages'
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # Compile the project using maven
      - name: Build with Maven
        run: 'mvn -B -Duser.name="GitHub Runner on $GITHUB_REPOSITORY (id=$GITHUB_RUN_ID)" clean package'

      # Upload the .jar files
      - name: 'Upload Build Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: McAuth-BungeeCord
          path: ./target/McAuth-BungeeCord.jar

      # Run static code analysis
      - name: 'SonarCloud.io (static code analysis)'
        run: 'mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
